/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Wed Feb  1 17:08:40 2017. */

#include "protocol.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t PubMsg_fields[7] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, PubMsg, clientID, clientID, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, PubMsg, guid, clientID, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, PubMsg, subject, guid, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, PubMsg, reply, subject, 0),
    PB_FIELD(  5, BYTES   , SINGULAR, STATIC  , OTHER, PubMsg, data, reply, 0),
    PB_FIELD( 10, BYTES   , SINGULAR, STATIC  , OTHER, PubMsg, sha256, data, 0),
    PB_LAST_FIELD
};

const pb_field_t PubAck_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, PubAck, guid, guid, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, PubAck, error, guid, 0),
    PB_LAST_FIELD
};

const pb_field_t MsgProto_fields[8] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, MsgProto, sequence, sequence, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, MsgProto, subject, sequence, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, MsgProto, reply, subject, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, STATIC  , OTHER, MsgProto, data, reply, 0),
    PB_FIELD(  5, INT64   , SINGULAR, STATIC  , OTHER, MsgProto, timestamp, data, 0),
    PB_FIELD(  6, BOOL    , SINGULAR, STATIC  , OTHER, MsgProto, redelivered, timestamp, 0),
    PB_FIELD( 10, UINT32  , SINGULAR, STATIC  , OTHER, MsgProto, CRC32, redelivered, 0),
    PB_LAST_FIELD
};

const pb_field_t Ack_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, Ack, subject, subject, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, Ack, sequence, subject, 0),
    PB_LAST_FIELD
};

const pb_field_t ConnectRequest_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, ConnectRequest, clientID, clientID, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, ConnectRequest, heartbeatInbox, clientID, 0),
    PB_LAST_FIELD
};

const pb_field_t ConnectResponse_fields[8] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, ConnectResponse, pubPrefix, pubPrefix, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, ConnectResponse, subRequests, pubPrefix, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, ConnectResponse, unsubRequests, subRequests, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, ConnectResponse, closeRequests, unsubRequests, 0),
    PB_FIELD(  5, STRING  , SINGULAR, STATIC  , OTHER, ConnectResponse, error, closeRequests, 0),
    PB_FIELD(  6, STRING  , SINGULAR, STATIC  , OTHER, ConnectResponse, subCloseRequests, error, 0),
    PB_FIELD(100, STRING  , SINGULAR, STATIC  , OTHER, ConnectResponse, publicKey, subCloseRequests, 0),
    PB_LAST_FIELD
};

const pb_field_t SubscriptionRequest_fields[11] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, SubscriptionRequest, clientID, clientID, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, SubscriptionRequest, subject, clientID, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, SubscriptionRequest, qGroup, subject, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, SubscriptionRequest, inbox, qGroup, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, SubscriptionRequest, maxInFlight, inbox, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, SubscriptionRequest, ackWaitInSecs, maxInFlight, 0),
    PB_FIELD(  7, STRING  , SINGULAR, STATIC  , OTHER, SubscriptionRequest, durableName, ackWaitInSecs, 0),
    PB_FIELD( 10, UENUM   , SINGULAR, STATIC  , OTHER, SubscriptionRequest, startPosition, durableName, 0),
    PB_FIELD( 11, UINT64  , SINGULAR, STATIC  , OTHER, SubscriptionRequest, startSequence, startPosition, 0),
    PB_FIELD( 12, INT64   , SINGULAR, STATIC  , OTHER, SubscriptionRequest, startTimeDelta, startSequence, 0),
    PB_LAST_FIELD
};

const pb_field_t SubscriptionResponse_fields[3] = {
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , FIRST, SubscriptionResponse, ackInbox, ackInbox, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, SubscriptionResponse, error, ackInbox, 0),
    PB_LAST_FIELD
};

const pb_field_t UnsubscribeRequest_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, UnsubscribeRequest, clientID, clientID, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, UnsubscribeRequest, subject, clientID, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, UnsubscribeRequest, inbox, subject, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, UnsubscribeRequest, durableName, inbox, 0),
    PB_LAST_FIELD
};

const pb_field_t CloseRequest_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, CloseRequest, clientID, clientID, 0),
    PB_LAST_FIELD
};

const pb_field_t CloseResponse_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, CloseResponse, error, error, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(PubMsg, data) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_PubMsg_PubAck_MsgProto_Ack_ConnectRequest_ConnectResponse_SubscriptionRequest_SubscriptionResponse_UnsubscribeRequest_CloseRequest_CloseResponse)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for PubMsg.data is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
